// <auto-generated />
namespace S2B2015.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class produtoidonperguntas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(produtoidonperguntas));
        
        string IMigrationMetadata.Id
        {
            get { return "201506072252468_produtoid on perguntas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
